services:
  postgres:
    image: postgres:16-alpine  
    environment:
      POSTGRES_DB: openbpl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-defaultpassword}  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:  

